import "./globals.css";
import type { Metadata } from "next";
import { Hahmlet } from "next/font/google";

const hahmlet = Hahmlet({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SPEED WEB",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={hahmlet.className}>{children}</body>
    </html>
  );
}
